Renamed to later date, further testing
Builds with the Dockerfile in the tutorial, but I get this error
when I try to run:

npm info it worked if it ends with ok
npm info using npm@2.14.12
npm info using node@v4.2.5
npm info prestart JawboneUpNodeDemo@0.0.1
npm info start JawboneUpNodeDemo@0.0.1

> JawboneUpNodeDemo@0.0.1 start /usr/src/app
> node server.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'body-parser'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/server.js:6:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

npm info JawboneUpNodeDemo@0.0.1 Failed to exec start script
npm ERR! Linux 3.18.21-1-rackos
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.5
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! JawboneUpNodeDemo@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the JawboneUpNodeDemo@0.0.1 start script 'node server.js'.
npm ERR! This is most likely a problem with the JawboneUpNodeDemo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls JawboneUpNodeDemo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

Any help is welcomed!